### ISSUE TITLE
Resurgent Soil behavior is inconsistent to rich soil

### ISSUE THREAD

**Issue by thelegitdolt** [SoyTutta/MyNethersDelight#14]
In vanilla FD, Rich Soils will not bone meal any blocks that are tagged with `#farmersdelight:unaffected_by_rich_soil`  [here](https://github.com/vectorwing/FarmersDelight/blob/1.19/src/generated/resources/data/farmersdelight/tags/blocks/unaffected_by_rich_soil.json))  to avoid unintentional behavior, like easy infinite crop farms with wild crop and the like. Resurgent Soil should do this check as well. 

 Also, the fungus colonies added in this mod never ticks because they share BlockProperties with their vanilla fungus counterparts, which do not have the .randomTicks() property. I think you should add that it would be cool.

**Comment by ssfwuu0721** [comment]
wait, Resurgent Soil can make many plants spread, like crops, wild crops, flowers, grass, sapling...is it a bug or desigh?
