### ISSUE TITLE
Render thread

### ISSUE THREAD

**Issue by 5A93** [SoyTutta/MyNethersDelight#2]
Crashed when trying to load the mod
[minecraft.log](https://github.com/SoyTutta/MyNethersDelight/files/15224747/minecraft.log)

**Comment by SoyTutta** [comment]
Can you confirm me if the new update solved your Crash?

**Comment by 5A93** [comment]
Seems to be fine by now. But the structures can't be located by command. Is that normal?

**Comment by 5A93** [comment]
> Can you confirm me if the new update solved your Crash?

Seems to be fine by now. But the structures can't be located by command. Is that normal?

**Comment by 5A93** [comment]
> yeah, because there are no structures in this mod xD the blog structures are just showcase- I'll add a clarification now on the page so people don't get confused because of me!

Shame, the ideal itself looks so appealing, maybe you can consider actually adding them. Thanks for the effort anyway!
