### ISSUE TITLE
[Bug?] Recipe Problems

### ISSUE THREAD

**Issue by SaltSouls** [SoyTutta/MyNethersDelight#26]
So I'm not sure if this is a bug or not, but the recipe for the deviled egg seems to be non-existent(I even checked the jar file), and the compatibility with Miners Delight seems to not be functioning at all. There are no copper cup variants of any of the MyNethersDelight soups or stews. Again, not sure if this is a bug as I am seeing the recipes in the jar, but I'm not seeing the items in game.

**Comment by SoyTutta** [comment]
I forgot to include them in the creative tab but the cups should be available if you make stews and soups in the copper pot-
as for the deviled egg, it can be prepared in any pot: boiled egg + blaze powder + bacon

I recommend to play with jei!

**Comment by SaltSouls** [comment]
> I forgot to include them in the creative tab but the cups should be available if you make stews and soups in the copper pot- as for the deviled egg, it can be prepared in any pot: boiled egg + blaze powder + bacon "src/generated/resources/data/mynethersdelight/recipes/cooking/boiled_egg.json"
> 
> I recommend to play with jei!

That's what I'm getting at. I am playing with JEI/EMI and there is no recipe for the deviled egg. Not even inside the jar file or on in the github repo. The recipe you just linked is for the boiled egg, not the deviled egg.

**Comment by SoyTutta** [comment]
the recipe has the wrong name yeah, but it is perfectly functional in-game
![JeiCapture](https://github.com/user-attachments/assets/bc3251e4-3f60-4ba3-9b7b-449ead482a56)
