### ISSUE TITLE
Offer to unofficially port My Nether's Delight to Fabric

### ISSUE THREAD

**Issue by MerchantPug** [SoyTutta/MyNethersDelight#37]
Hi, I'm MerchantPug, one of the devs for Farmer's Delight Refabricated.

Would you mind if I unofficially ported My Nether's Delight to the Refabricated port/Fabric modloader.

I would keep the codebase as similar as possible, and would make sure that I say the port is unofficial and to report issues with it over to my repo.

Thanks for reading this.

**Comment by ChrysanthCow** [comment]
Resolved through Discord DMs. I will be making a port.
